name: ğŸ§  SonarQube Analysis

on:
  workflow_dispatch:
  push:
    branches: [live]

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“‚ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: ğŸ“¦ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ§ª Run tests & generate coverage
        run: pnpm test:coverage

      - name: ğŸ§  Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          pnpm exec sonar-scanner \
            -Dproject.settings=sonar-project.properties
